### ISSUE TITLE
dmtxwrite fails to build 10x10 barcode

### ISSUE THREAD

**Issue by Mesibov** [dmtx/dmtx-utils#19]
I get a "dmtxwrite: Unable to encode message (possibly too large for requested size)" message when trying to barcode a 3-character message (like "W6x") with the -s 10x10 option. A 12x12 barcode is correctly built with the -s 12x12 option.

Online barcode generators build a 10x10 with 3 characters without a problem, and these get read by dmtxread as shown:
Matrix Size: 10 x 10
Data Codewords: 3 (capacity 3)
Error Codewords: 5
Data Regions: 1 x 1
Interleaved Blocks: 1
Rotation Angle: 0

**Comment by msva** [comment]
I guess, the problem is in that you have newline character in addition to your "3 characters".
if you're using something like
```
echo 'aaa' | dmtxwrite -s 10x10
```
then `echo` adds a newline character to the end of the message.
You can try to use
```
echo -n 'aaa' | dmtxwrite -s 10x10
```
And get it to work (there will be exactly 3 characters, without newline).

And if you're encode the file, and not an "echo" output - just remove newline character on it's end.

(you can notice it's existance by `xxd`, for example)

```
$ echo -n 'aaa' | xxd -i 
  0x61, 0x61, 0x61
$ echo 'aaa' | xxd -i
  0x61, 0x61, 0x61, 0x0a
```

**Comment by Mesibov** [comment]
Many thanks!
